#!/usr/bin/env bash

: "${HOME:=/Users/tamouse}"
LOGSEQ_DIR="$HOME/Logseq.local"

/usr/local/bin/keybase fs cp -r -f "$LOGSEQ_DIR" /keybase/private/tamouse_/Logseq.backup/$(date "+%Y-%m-%d-%H-%M-%S")
