#!/usr/bin/env ruby
# freeze-string-literals: true

def rename_basename(old)
  dir = File.dirname(old)
  ext = File.extname(old)
  base = File.basename(old, ext)
  base = base.downcase.strip.gsub(/[^[:alnum:]]+/, @separator)
  base = [base, ext].join
  [dir, base].join(File::SEPARATOR)
end

@separator='_'

while ARGV[0].start_with?('-')
  switch = ARGV.shift
  case switch
  when '-s'
    sep=ARGV.shift
    @separator=sep[0] if sep != nil
  else
    ; # Do nothing
  end
end

ARGV.each do |old|
  new=rename_basename(old)
  puts "Renaming #{old} => #{new} using #{@separator}"
  File.rename(old, new)
end
